import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { CheckCircle2, Shield, Scale, Eye, ClipboardCheck } from 'lucide-react';
import { MetricTooltip } from '@/components/metrics/MetricTooltip';

interface ChecklistItem {
  key: string;
  text: string;
}

const sections: { title: string; icon: React.ReactNode; items: ChecklistItem[] }[] = [
  {
    title: 'Privacy',
    icon: <Shield className="w-4 h-4 text-indigo-500" />,
    items: [
      { key: 'privacy-data-detected', text: 'PII detection scan performed on resume text' },
      { key: 'privacy-sensitive-info', text: 'Sensitive information check completed' },
      { key: 'privacy-session-storage', text: 'Resume text held in session memory only — not persisted to any server or database' },
    ],
  },
  {
    title: 'Fairness',
    icon: <Scale className="w-4 h-4 text-indigo-500" />,
    items: [
      { key: 'fairness-no-protected-attributes', text: 'Analysis ignores name, age, gender, ethnicity, and other protected characteristics' },
      { key: 'fairness-job-related-only', text: 'All feedback based solely on job-relevant criteria' },
    ],
  },
  {
    title: 'Transparency',
    icon: <Eye className="w-4 h-4 text-indigo-500" />,
    items: [
      { key: 'transparency-ai-generated', text: 'All recommendations on this page were generated by AI, not a human career coach' },
      { key: 'transparency-human-review', text: 'We recommend reviewing AI suggestions with a human before making major resume changes' },
    ],
  },
  {
    title: 'Governance',
    icon: <ClipboardCheck className="w-4 h-4 text-indigo-500" />,
    items: [
      { key: 'governance-audit-log', text: 'Analysis session record viewable in the AI Request Insights panel above' },
      { key: 'governance-prompt-version', text: 'Prompt version tracked and displayed for reproducibility' },
      { key: 'governance-model-version', text: 'Exact AI model and version recorded' },
    ],
  },
];

export function ResponsibleAICard() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Responsible AI Dashboard</CardTitle>
        <CardDescription>
          How this application handles privacy, fairness, transparency, and governance.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {sections.map((section, si) => (
          <div key={section.title}>
            {si > 0 && <Separator className="mb-6" />}
            <div className="flex items-center gap-2 mb-3">
              {section.icon}
              <h3 className="text-sm font-semibold text-foreground">{section.title}</h3>
            </div>
            <div className="space-y-2">
              {section.items.map((item) => (
                <div key={item.key} className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                  <MetricTooltip metricKey={item.key}>
                    <span className="text-sm text-foreground">{item.text}</span>
                  </MetricTooltip>
                </div>
              ))}
            </div>
          </div>
        ))}

        <Separator />

        <div className="flex items-center justify-between pt-2">
          <div className="flex items-center gap-2">
            <MetricTooltip metricKey="risk-assessment">
              <span className="text-sm font-medium text-foreground">Risk Level:</span>
            </MetricTooltip>
          </div>
          <Badge variant="success">Low</Badge>
        </div>

        <p className="text-[10px] text-muted-foreground leading-relaxed">
          These represent the design-time safeguards built into this application.
        </p>
      </CardContent>
    </Card>
  );
}