import { useState } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { MetricTooltip } from '@/components/metrics/MetricTooltip';
import { Check, CaretDown } from '@phosphor-icons/react';
import { cn } from '@/lib/utils';

interface ChecklistItem {
  key: string;
  text: string;
}

const sections: { title: string; items: ChecklistItem[] }[] = [
  {
    title: 'Privacy',
    items: [
      { key: 'privacy-data-detected', text: 'PII detection scan performed on resume text' },
      { key: 'privacy-sensitive-info', text: 'Sensitive information check completed' },
      { key: 'privacy-session-storage', text: 'Resume text held in session memory only — not persisted to any server or database' },
    ],
  },
  {
    title: 'Fairness',
    items: [
      { key: 'fairness-no-protected-attributes', text: 'Analysis ignores name, age, gender, ethnicity, and other protected characteristics' },
      { key: 'fairness-job-related-only', text: 'All feedback based solely on job-relevant criteria' },
    ],
  },
  {
    title: 'Transparency',
    items: [
      { key: 'transparency-ai-generated', text: 'All recommendations on this page were generated by AI, not a human career coach' },
      { key: 'transparency-human-review', text: 'We recommend reviewing AI suggestions with a human before making major resume changes' },
    ],
  },
  {
    title: 'Governance',
    items: [
      { key: 'governance-audit-log', text: 'Analysis session record viewable in the AI Request Insights panel above' },
      { key: 'governance-prompt-version', text: 'Prompt version tracked and displayed for reproducibility' },
      { key: 'governance-model-version', text: 'Exact AI model and version recorded' },
    ],
  },
];

export function ResponsibleAICard() {
  const [open, setOpen] = useState(false);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card>
        <CollapsibleTrigger asChild>
          <CardHeader className="cursor-pointer select-none hover:bg-secondary/30 transition-colors rounded-t-[var(--radius)]">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-[15px]">Responsible AI</CardTitle>
                <CardDescription className="text-[12px] sm:text-[13px]">
                  How this application handles privacy, fairness, transparency, and governance.
                </CardDescription>
              </div>
              <CaretDown
                size={16}
                weight="bold"
                className={cn(
                  'text-muted-foreground transition-transform duration-200 shrink-0 ml-3',
                  open && 'rotate-180'
                )}
              />
            </div>
          </CardHeader>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <CardContent className="space-y-0">
            {sections.map((section, si) => (
              <div key={section.title}>
                {si > 0 && <Separator className="my-4 sm:my-5" />}
                <p className="text-[10px] font-medium text-muted-foreground uppercase tracking-[0.12em] mb-2 sm:mb-3">
                  {section.title}
                </p>
                <div className="space-y-2 sm:space-y-2.5">
                  {section.items.map((item) => (
                    <div key={item.key} className="flex items-start gap-3">
                      <Check size={14} weight="bold" className="text-foreground/40 mt-px shrink-0" />
                      <MetricTooltip metricKey={item.key}>
                        <span className="text-[12px] sm:text-[13px] text-foreground leading-relaxed">{item.text}</span>
                      </MetricTooltip>
                    </div>
                  ))}
                </div>
              </div>
            ))}

            <Separator className="my-4 sm:my-5" />

            <div className="flex items-center justify-between">
              <MetricTooltip metricKey="risk-assessment">
                <span className="text-[11px] text-muted-foreground">Risk Level</span>
              </MetricTooltip>
              <Badge variant="success">Low</Badge>
            </div>

            <p className="text-[10px] text-muted-foreground/60 mt-3 leading-relaxed">
              These represent the design-time safeguards built into this application.
            </p>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}