import { useState } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Check, CaretDown } from '@phosphor-icons/react';
import { cn } from '@/lib/utils';

interface ChecklistItem {
  text: string;
}

const sections: { title: string; items: ChecklistItem[] }[] = [
  {
    title: 'Privacy',
    items: [
      { text: 'PII detection scan performed on resume text' },
      { text: 'Sensitive information check completed' },
      { text: 'Resume text held in session memory only — not persisted' },
    ],
  },
  {
    title: 'Fairness',
    items: [
      { text: 'Analysis ignores name, age, gender, ethnicity, and protected characteristics' },
      { text: 'All feedback based solely on job-relevant criteria' },
    ],
  },
  {
    title: 'Transparency',
    items: [
      { text: 'All recommendations generated by AI, not a human career coach' },
      { text: 'We recommend reviewing AI suggestions with a human before making major changes' },
    ],
  },
  {
    title: 'Governance',
    items: [
      { text: 'Analysis session record viewable in the AI Request Insights panel' },
      { text: 'Prompt version tracked and displayed for reproducibility' },
      { text: 'Exact AI model and version recorded' },
    ],
  },
];

export function ResponsibleAICard() {
  const [open, setOpen] = useState(false);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card>
        <CollapsibleTrigger asChild>
          <CardHeader className="cursor-pointer select-none hover:bg-secondary/30 transition-colors rounded-t-[var(--radius)]">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-[15px]">Responsible AI</CardTitle>
                <CardDescription>
                  Privacy, fairness, transparency, and governance safeguards.
                </CardDescription>
              </div>
              <CaretDown
                size={16}
                weight="bold"
                className={cn(
                  'text-muted-foreground transition-transform duration-200 shrink-0 ml-3',
                  open && 'rotate-180'
                )}
              />
            </div>
          </CardHeader>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <CardContent className="space-y-0">
            {sections.map((section, si) => (
              <div key={section.title}>
                {si > 0 && <Separator className="my-4" />}
                <p className="text-[10px] font-medium text-muted-foreground uppercase tracking-[0.12em] mb-3">
                  {section.title}
                </p>
                <ul className="space-y-2.5">
                  {section.items.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2.5">
                      <Check size={14} weight="bold" className="text-foreground/30 mt-px shrink-0" />
                      <span className="text-[13px] text-foreground leading-relaxed">{item.text}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}

            <Separator className="my-4" />

            <div className="flex items-center justify-between">
              <span className="text-[11px] text-muted-foreground">Risk Level</span>
              <Badge variant="success">Low</Badge>
            </div>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}